POST http://nutrient-doser-v2.lan/ota HTTP/1.1
content-type: application/json

{
    "uri": "http://KPC.lan:8000/ota.bin"
}

###
GET http://nutrient-doser-v2.lan/full-status HTTP/1.1

###
GET http://nutrient-doser-v2.lan/status HTTP/1.1

###
GET http://nutrient-doser-v2.lan/reboot HTTP/1.1

###
POST http://nutrient-doser-v2.lan/dispense HTTP/1.1
content-type: application/json

{
    "reqs": [
        {
            "motor_idx": 0,
            "ml": 30
        },
        {
            "motor_idx": 1,
            "ml": 30
        },
        {
            "motor_idx": 2,
            "ml": 30
        },
        {
            "motor_idx": 3,
            "ml": 30
        },
        {
            "motor_idx": 4,
            "ml": 30
        }
    ]
}

###
POST http://nutrient-doser-v2.lan/dose HTTP/1.1
content-type: application/json

{
    "nutrients": [],
    "target_amount": 1.0,
    "target_unit": "L"
}

###
POST http://nutrient-doser-v2.lan/update-prime HTTP/1.1
content-type: application/json

{
    "motor_idx": 4,
    "prime_steps": 3600
}

###
POST http://nutrient-doser-v2.lan/unprime HTTP/1.1
content-type: application/json

{
    "motor_idx": 1
}

###
POST http://nutrient-doser-v2.lan/unprime-all HTTP/1.1

###
POST http://nutrient-doser-v2.lan/calibrate HTTP/1.1
content-type: application/json

{
    "motor_idx": 2,
    "expected": 10.0,
    "actual": 11.781
}

###
POST http://nutrient-doser-v2.lan/debug/step HTTP/1.1
content-type: application/json

{
    "motor_idx": 4,
    "steps": 8000
}

###
POST http://nutrient-doser-v2.lan/debug/calibrate HTTP/1.1
content-type: application/json

{
    "motor_idx": 2,
    "value": 0.00032
}

###
POST http://nutrient-doser-v2.lan/debug/clear-config HTTP/1.1
